# fly.toml app configuration file generated for deno-kv-marmot on 2023-07-16T21:57:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deno-kv-marmot"
primary_region = "den"

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
